### ISSUE TITLE
Subject Contacts Favorites

### ISSUE THREAD

**Issue by chrisewcs** [ruditimmer/launcher-modular#1]
Numbers are not passed to the phone application 
0151 or 0152 is passed some 0151 numbers are also not transferred. Strange?
0156 or 0175 is not transferred
Numbers with +49 are also not passed.

Messages application works with all numbers including +49.

**Comment by ruditimmer** [comment]
I will see i can reproduce as i'm not living into Germany... but it try to find the problem...

**Comment by ruditimmer** [comment]
Do you have saved your contacts number as Phone number or as mobile number ?
